apiVersion: v1
kind: Namespace
metadata:
  name: complyeaze-tools
  labels:
    app.kubernetes.io/name: complyeaze-tools
    app.kubernetes.io/component: static-site
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
