apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: complyeaze-tools-deployer
  namespace: complyeaze-tools
  labels:
    app.kubernetes.io/name: complyeaze-tools
    app.kubernetes.io/component: deploy-access
    app.kubernetes.io/part-of: complyeaze-tools
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
